# Generated by Django 5.2.4 on 2025-07-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='The unique username for logging in.', max_length=100, unique=True)),
                ('password_hash', models.CharField(help_text='Stores the hashed password for the user.', max_length=255)),
                ('full_name', models.CharField(help_text="The user's full name.", max_length=255)),
                ('role', models.ForeignKey(help_text='The role assigned to this user.', on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='roles.role')),
            ],
            options={
                'verbose_name': 'Application User',
                'verbose_name_plural': 'Application Users',
                'db_table': 'app_user',
            },
        ),
    ]
