# Generated by Django 5.2.4 on 2025-07-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(default=1, help_text='The role assigned to this user.', on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='roles.role'),
        ),
    ]
