# Generated by Django 5.2.4 on 2025-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_full_name', models.CharField(help_text='Full name of the deceased person.', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth of the deceased.', null=True)),
                ('date_of_death', models.DateField(help_text='Date of death of the deceased.')),
                ('date_of_burial', models.DateField(help_text='Date the burial took place.')),
                ('remains_type', models.CharField(choices=[('Fresh Body', 'Fresh Body'), ('Skeletal', 'Skeletal')], help_text='The type of remains that were interred.', max_length=20)),
            ],
            options={
                'verbose_name': 'Burial',
                'verbose_name_plural': 'Burials',
                'db_table': 'burial',
                'ordering': ['-date_of_burial'],
            },
        ),
    ]
