# Generated by Django 5.2.4 on 2025-07-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('burials', '0001_initial'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burial',
            name='lot',
            field=models.ForeignKey(help_text='The lot where this burial took place.', on_delete=django.db.models.deletion.RESTRICT, related_name='burials', to='lots.lot'),
        ),
    ]
