# Generated by Django 5.2.4 on 2025-07-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='The unique name of the lot type (e.g., Gold, Platinum).', max_length=50, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='The base purchase price for a lot of this type.', max_digits=12)),
                ('max_fresh_body_capacity', models.IntegerField(help_text='Maximum number of fresh body remains allowed.')),
                ('max_skeletal_remains_capacity', models.IntegerField(help_text='Maximum number of skeletal remains allowed.')),
                ('description', models.TextField(blank=True, help_text='A detailed description of the lot type.', null=True)),
            ],
            options={
                'verbose_name': 'Lot Type',
                'verbose_name_plural': 'Lot Types',
                'db_table': 'lot_type',
            },
        ),
    ]
