# Generated by Django 5.2.4 on 2025-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="The client's full name.", max_length=255)),
                ('contact_number', models.CharField(blank=True, help_text="The client's primary contact number.", max_length=20, null=True, unique=True)),
                ('email_address', models.EmailField(blank=True, help_text="The client's email address.", max_length=255, null=True, unique=True)),
                ('mailing_address', models.TextField(blank=True, help_text="The client's physical mailing address.", null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
    ]
