# Generated by Django 5.2.4 on 2025-07-29 15:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('lot_count', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
