# Generated by Django 5.2.4 on 2025-07-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='block',
        ),
    ]
