# Generated by Django 5.2.4 on 2025-07-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The exact time the action occurred.')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='The type of action performed (Create, Update, Delete).', max_length=20)),
                ('entity_affected', models.CharField(help_text='The model or table that was affected by the action.', max_length=50)),
                ('record_id', models.IntegerField(blank=True, help_text='The primary key of the record that was affected.', null=True)),
                ('change_details', models.JSONField(blank=True, help_text='A JSON object detailing the changes (e.g., old and new values).', null=True)),
                ('user', models.ForeignKey(help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.appuser')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
