# Generated by Django 5.2.4 on 2025-07-19 12:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('lottypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold')], default='Available', help_text='The current availability status of the lot.', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The geographic location (Point) of the lot.', null=True, srid=4326)),
                ('client', models.ForeignKey(blank=True, help_text='The client who owns this lot. Can be empty if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='clients.client')),
                ('lot_type', models.ForeignKey(help_text='The type of this lot.', on_delete=django.db.models.deletion.RESTRICT, related_name='lots', to='lottypes.lottype')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'lot',
                'unique_together': {('block', 'section', 'lot_number')},
            },
        ),
    ]
