# Generated by Django 5.2.4 on 2025-07-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='fresh_body_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='skeletal_remains_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
