# Generated by Django 5.2.4 on 2025-07-27 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burials', '0002_initial'),
        ('lots', '0002_lot_fresh_body_count_lot_skeletal_remains_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotOccupancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remains_type', models.CharField(max_length=20)),
                ('change', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('burial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='burials.burial')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.lot')),
            ],
        ),
    ]
