# Generated by Django 5.2.4 on 2025-07-29 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_lotoccupancyhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='The geographic location (Polygon) of the lot.', null=True, srid=4326),
        ),
    ]
