# Generated by Django 5.2.4 on 2025-07-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_alter_block_table'),
        ('lots', '0004_alter_lot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='block',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.block'),
        ),
    ]
