# Generated by Django 5.2.4 on 2025-07-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the notification message.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the user has read the notification.')),
                ('related_entity_type', models.CharField(blank=True, help_text="The type of entity this notification relates to (e.g., 'Payment').", max_length=50, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, help_text='The ID of the related entity.', null=True)),
                ('user', models.ForeignKey(help_text='The user this notification is for.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.appuser')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
