# Generated by Django 5.2.4 on 2025-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='The date when the payment is due.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Card', 'Card')], default='Cash', help_text='The method used to make the payment.', max_length=20),
        ),
    ]
